exclude:
- README.md

gems:
  - jekyll-redirect-from
  - jekyll-sitemap

timezone: Europe/Berlin

title: Wurst Client

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"